# Generated by Django 4.1.7 on 2023-05-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProd', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About me', 'verbose_name_plural': 'About me'},
        ),
        migrations.AlterField(
            model_name='recentwork',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Work title'),
        ),
    ]
