# Generated by Django 4.1.7 on 2023-05-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProd', '0002_alter_about_options_alter_recentwork_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='team name')),
                ('image', models.ImageField(upload_to='team')),
            ],
        ),
    ]
